export const AUTH = 'AUTH';
export const FETCH_SINGLEUSER = 'FETCH_SINGLEUSER';
export const LOGOUT = 'LOGOUT';
export const UPDATE_SINGLE_USER = 'UPDATE_SINGLE_USER';
export const FETCH_HOMEPAGE = 'FETCH_HOMEPAGE';
export const CREATE_HOMEPAGE = 'CREATE_HOMEPAGE';
export const START_HOMEPAGE = 'START_HOMEPAGE';
export const END_HOMEPAGE = 'END_HOMEPAGE';