export const AUTH = "AUTH";
export const FETCH_SINGLEUSER = "FETCH_SINGLEUSER";
export const LOGOUT = "LOGOUT";
export const UPDATE_SINGLE_USER = "UPDATE_SINGLE_USER";
export const FETCH_HOMEPAGE = "FETCH_HOMEPAGE";
export const CREATE_HOMEPAGE = "CREATE_HOMEPAGE";
export const START_HOMEPAGE = "START_HOMEPAGE";
export const END_HOMEPAGE = "END_HOMEPAGE";

// Add room by Admin
export const ROOM_CREATE_REQUEST = "ROOM_CREATE_REQUEST";
export const ROOM_CREATE_SUCCESS = "ROOM_CREATE_SUCCESS";
export const ROOM_CREATE_FAIL = "ROOM_CREATE_FAIL";
export const ROOM_CREATE_RESET = "ROOM_CREATE_RESET";

// List of rooms
export const ROOM_LIST_REQUEST = "ROOM_LIST_REQUEST";
export const ROOM_LIST_SUCCESS = "ROOM_LIST_SUCCESS";
export const ROOM_LIST_FAIL = "ROOM_LIST_FAIL";

// Contact Us
export const CONTACT_US_REQUEST = "CONTACT_US_REQUEST";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAIL = "CONTACT_US_FAIL";
export const CONTACT_US_RESET = "CONTACT_US_RESET";

// Contact Us List
export const CONTACT_US_LIST_REQUEST = "CONTACT_US_LIST_REQUEST";
export const CONTACT_US_LIST_SUCCESS = "CONTACT_US_LIST_SUCCESS";
export const CONTACT_US_LIST_FAIL = "CONTACT_US_LIST_FAIL";

// List of Booked rooms
export const ROOM_BOOKED_LIST_REQUEST = "ROOM_BOOKED_LIST_REQUEST";
export const ROOM_BOOKED_LIST_SUCCESS = "ROOM_BOOKED_LIST_SUCCESS";
export const ROOM_BOOKED_LIST_FAIL = "ROOM_BOOKED_LIST_FAIL";

// Update room by Admin
export const ROOM_UPDATE_REQUEST = "ROOM_UPDATE_REQUEST";
export const ROOM_UPDATE_SUCCESS = "ROOM_UPDATE_SUCCESS";
export const ROOM_UPDATE_FAIL = "ROOM_UPDATE_FAIL";
export const ROOM_UPDATE_RESET = "ROOM_UPDATE_RESET";

// Room Booking By Client
export const ROOM_BOOK_REQUEST = "ROOM_BOOK_REQUEST";
export const ROOM_BOOK_SUCCESS = "ROOM_BOOK_SUCCESS";
export const ROOM_BOOK_FAIL = "ROOM_BOOK_FAIL";

// Single Room Details
export const ROOM_DETAILS_REQUEST = "ROOM_DETAILS_REQUEST";
export const ROOM_DETAILS_SUCCESS = "ROOM_DETAILS_SUCCESS";
export const ROOM_DETAILS_FAIL = "ROOM_DETAILS_FAIL";
