export const AUTH = 'AUTH';
export const FETCH_SINGLEUSER = 'FETCH_SINGLEUSER';
export const ERROR_AUTH_SIGNIN = 'ERROR_AUTH_SIGNIN';
export const ERROR_AUTH_SIGNUP = 'ERROR_AUTH_SIGNUP';
export const LOGOUT = 'LOGOUT';
export const UPDATE_SINGLE_USER = 'UPDATE_SINGLE_USER';